curl -X GET "https://api.cloudflare.com/client/v4/user/tokens/verify" \
     -H "Authorization: Bearer k..Ik_jY0..3wM_re..CRD" \
     -H "Content-Type:application/json"
-H apl CloudFlare information = [{16WfJ...Sge}],

-H </v1.0-e0b279492afa7f006ea73fe7-fcef1dbcfddde059728f6d32301ec78ca4f8382dfe08afa33a43da414c6446e7f4fe208d99dfa97d23c3ba621aba914ae6d40353846b1f61c2f0e69b469657786e788405470802b8e7/>
-H yere.steph@gmail.com 
-H environment check
52...7cc46e030(true)

important 
-H 
< if system name this project main (false)action block 
