name: REUSE Compliance Check

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    - name: REUSE Compliance Check
      uses: fsfe/reuse-action@v1

[![REUSE Compliance Check](https://github.com/npm/documentation/actions/workflows/license-compliance.yml/badge.svg)](https://github.com/npm/documentation/actions/workflows/license-compliance.yml)
