      # Check if all the necessary template-oss changes were applied. Since we continued
      # on errors in one of the previous steps, this check will fail if our follow up
      # only applied a portion of the changes and we need to followup manually.
      #
      # Note that this used to run `lint` and `postlint` but that will fail this action
      # if we've also shipped any linting changes separate from template-oss. We do
      # linting in another action, so we want to fail this one only if there are
      # template-oss changes that could not be applied.
      - name: Check Changes
        if: steps.apply.outputs.changes
        run: |
          npm exec --offline ${{ steps.flags.outputs.workspace }} -- template-oss-check

      - name: Fail on Breaking Change
        if: steps.apply.outputs.changes && startsWith(steps.apply.outputs.message, 'feat!')
        run: |
          echo "This PR has a breaking change. Run 'npx -p @npmcli/stafftools gh template-oss-fix'"
          echo "for more information on how to fix this with a BREAKING CHANGE footer."
          exit 1
